import arrow
from datetime import datetime
from dateutil import tz
i = arrow.get(1857900545)
print("Date from integers: ")
print(i)
f = arrow.get(1857900545.234323)
print("\nDate from floats: ")
print(f)
#s = arrow.get('1857900545')
#print("\nDate from Strings: ")
#print(s)
print("\nCreate a date from a given date and a given time zone:")
d1 = arrow.get(datetime(2018, 7, 5), 'US/Pacific')
print(d1)
print("\nCreate a date from a given date and a time zone object from a string representation:")
d2 = arrow.get(datetime(2017, 7, 5), tz.gettz('America/Chicago'))
print(d2)
d3 = arrow.get(datetime.now(tz.gettz('US/Pacific')))
print("\nCreate a date using current datetime and a specified time zone:")
print(d3)
a = arrow.utcnow()
print("Datetime representation:")
print(a.datetime)
b = a.timestamp
print("\nTimestamp representation:")
print(b)
a = arrow.utcnow()
print(arrow.utcnow())
print("Hour ceiling:")
print(arrow.utcnow().ceil('hour'))
print("\nMinute ceiling:")
print(arrow.utcnow().ceil('minute'))
print("\nSecond ceiling:")
print(arrow.utcnow().ceil('second')) 
print("Year:")
print(a.year)
print("\nMonth:")
print(a.month)
print("\nDate:")
print(a.day)
print("Test whether a given datetime is between two dates and times:")
start = arrow.get(datetime(2017, 6, 5, 12, 30, 10))
end = arrow.get(datetime(2017, 6, 5, 12, 30, 36))
print(arrow.get(datetime(2017, 6, 5, 12, 30, 27)).is_between(start, end))
start = arrow.get(datetime(2017, 5, 5))
end = arrow.get(datetime(2017, 5, 8))
print(arrow.get(datetime(2017, 5, 8)).is_between(start, end, '[]'))
start = arrow.get(datetime(2017, 5, 5))
end = arrow.get(datetime(2017, 5, 8))
print(arrow.get(datetime(2017, 5, 8)).is_between(start, end, '[)'))
